#ifndef _DEFINES_H
#define _DEFINES_H

#define PI 3.1415926


#define PATCH_POWER_OF_2 7
#define PATCH_WIDTH (1<<PATCH_POWER_OF_2)
#define PATCH_SIZE (PATCH_WIDTH+1)
#define NUM_PATCH_VERTICES (PATCH_SIZE*PATCH_SIZE)
#define PATCH_SCALE 20.0f
#define PATCH_WORLD_WIDTH (PATCH_SCALE*PATCH_WIDTH)
#define INV_PATCH_WORLD_WIDTH (1.0f/PATCH_WORLD_WIDTH)
#define HALF_PATCH_WORLD_WIDTH (PATCH_WORLD_WIDTH*0.5f)
#define HEIGHT_SCALE (256.0f/256.0f)
#define TEX_COORD_RANGE 8.0f


#endif