//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GameServer2.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     102
#define IDC_LIST                        1000
#define IDC_EDIT1                       1001
#define IDSTART                         1002
#define IDC_LIST2                       1004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
