#define NOP -1
#define  AMBERSAND 0
#define  AMBERSANDASSIGN 1
#define  AND 2
#define  ANDASSIGN 3
#define  ASSIGN 4
#define  CAP 5
#define  CAPASSIGN 6
#define  DIV 7
#define  DIVASSIGN 8
#define  EQ 9
#define  GE 10
#define  GOTO 11
#define  GT 12
#define  GTGTASSIGN 13
#define  IFEQ 14
#define  LE 15
#define  LT 16
#define  LTLTASSIGN 17
#define  MUL 18
#define  MULASSIGN 19
#define  MINUS 20
#define  MINUSASSIGN 21
#define  MINUSMINUS 22
#define  MOD 23
#define  MODASSIGN 24
#define  NE 25
#define  OR 26
#define  ORASSIGN 27
#define  PLUS 28
#define  PLUSASSIGN 29
#define  PLUSPLUS 30
#define  SIZEOF 31
#define  STAR 32
#define  TILDE 33
#define  TILDEASSIGN 34
#define  UMINUS 35
#define  UPLUS 36
#define  RASSIGN 37
#define LASSIGN 38
