//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ase.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_ASETYPE                     129
#define IDB_NODEICONS                   130
#define ID_PATHING_ASSUMEDTHREATMOVEMENT 133
#define ID_ASSUMEDTHREATMOVEMENT_NOTHREATMOVEMENT 134
#define ID_ASSUMEDTHREATMOVEMENT_THREATSMOVE1CELL 135
#define ID_ASSUMEDTHREATMOVEMENT_THREATSMOVE2CELLS 136
#define IDC_DRAWTYPE                    1001
#define ID_WEIGHT0                      32773
#define ID_WEIGHT20                     32774
#define ID_WEIGHT40                     32775
#define ID_WEIGHTIMPASSABLE             32776
#define ID_STARTINGPOINT                32777
#define ID_ENDPOINT                     32778
#define ID_ENEMYPOSITION                32779
#define ID_THREATPOSITION               32779
#define ID_EXECUTEASTAR                 32783
#define ID_STEPASTAR                    32785
#define ID_EDIT_CLEARBOARD              32786
#define ID_PATHING_ALLOWDIAGONAL        32787
#define ID_PATHING_CONTINUOUSUPDATE     32788
#define ID_PATHING_DISPLAYGOALNODE      32789
#define ID_VIEW_AROUTE                  32790
#define ID_RUNTOBREAKPOINT              32791
#define ID_PATHING_BREAKPOINTS_POINT    32796
#define ID_PATHING_BREAKPOINTS_OLUPDATE 32797
#define ID_PATHING_BREAKPOINTS_OLCHILD  32798
#define ID_PATHING_BREAKPOINTS_CLUPDATE 32799
#define ID_PATHING_BREAKPOINTS_CLCHILD  32800
#define ID_PATHING_BREAKPOINTS_NEWCHILD 32801
#define ID_PATHING_RELATIVECOSTING      32806
#define ID_PATHING_SLOWMOTION           32807
#define ID_MOVEMENT_MANHATTAN           61204
#define ID_MOVEMENT_DIAGONAL            61205
#define ID_MOVEMENTCOSTS_CELL           61217
#define ID_MOVEMENTCOSTS_VECTOR         61218
#define ID_MOVEMENTCOSTS_RELATIVE       61219
#define ID_THREATCOSTS_NONE             62209
#define ID_THREATCOSTS_LINEOFFIRE       62210
#define ID_THREATCOSTS_LOFWITHMEMORY    62211
#define ID_THREATCOSTS_THREATCOUNT      62212
#define ID_THREATCOSTS_THREATSNONSTATIC 62213
#define ID_THREATCOSTS_DISTANCETOTHREAT 62214
#define ID_THREATCOSTS_APPROXLUT        62215
#define ID_VIEW_SEARCHSPACE             63111
#define ID_VIEW_THREATS                 63112
#define ID_VIEW_LOF                     63113
#define ID_VIEW_APPROX_LOF              63114
#define ID_THREATMOVEMENT_0             63121
#define ID_THREATMOVEMENT_1             63122
#define ID_THREATMOVEMENT_2             63123

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        137
#define _APS_NEXT_COMMAND_VALUE         32817
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
