//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by csg_bsp.rc
//
#define IDD_ABOUTBOX                    100
#define IDC_CROTATE                     122
#define IDR_MAINFRAME                   128
#define IDR_Z_ED2TYPE                   129
#define IDC_SCROLL                      131
#define IDC_CSCALE                      133
#define IDD_DIALOG1                     134
#define DLG_TEX                         134
#define IDC_CURSOR3                     135
#define IDC_CMOVE                       136
#define IDB_ABOUTMAR                    139
#define IDR_MENU1                       140
#define DLG_FACESET                     141
#define DLG_NEWBRUSH                    143
#define DLG_GS                          144
#define IDB_BITMAP1                     146
#define TB_ALIGN                        150
#define TB_QUADRAICS                    151
#define DLG_WAIT                        152
#define DLG_BRUSHSET                    153
#define DLG_BRSHPRP                     154
#define IDR_DLGPROGRESS                 155
#define BMP_DEF                         155
#define DLG_COMPILERPROG                155
#define DLG_F_SET                       156
#define DLG_B_SET                       157
#define DLG_COMPILESET                  158
#define IDC_CURSOR1                     159
#define DLG_ITEMS                       159
#define DLG_SCRIPT                      160
#define DLG_SOUNDS                      161
#define IDB_BITMAP2                     161
#define DLG_TRIGERS                     162
#define IDD_DIALOG2                     162
#define DLG_SKYDOM                      163
#define IDB_BITMAP3                     163
#define DLG_SCENE                       164
#define IDC_STATICF                     1000
#define IDC_BUTTON1                     1001
#define IDC_STATICF2                    1001
#define ST_TEXPATH                      1002
#define PC_CLOSE                        1002
#define PB_PREV                         1003
#define PB_NEXT                         1004
#define IDC_CHECK1                      1005
#define CK_TRANSPARENT                  1005
#define CK_SHOWBACK                     1005
#define IDC_CHECK2                      1006
#define EF_NOCOLIDE                     1006
#define CK_NOCOLIDE                     1006
#define IDC_CHECK3                      1007
#define EF_NOLIGHT                      1007
#define CK_NOLIGHT                      1007
#define CK_REMES                        1007
#define ST_NAME                         1008
#define CK_TRANSPARENT2                 1008
#define CK_MIRROR                       1008
#define CK_REM1POLYL                    1008
#define CK_PVS                          1008
#define ST_SIZE                         1009
#define IDC_CHECK8                      1009
#define CK_METALIC                      1009
#define ST_BPP                          1010
#define IDC_CHECK10                     1010
#define CK_SAVEINFILE                   1010
#define PB_APPLYTEX                     1011
#define IDC_LIST1                       1012
#define IDC_RADIO1                      1014
#define IDC_RADIO2                      1015
#define IDC_RADIO3                      1016
#define IDC_RADIO4                      1017
#define RB_RADIAL                       1017
#define IDC_EDIT2                       1018
#define IDC_RADIO5                      1018
#define RB_SPIN                         1018
#define IDC_SPIN1                       1019
#define IDC_EDIT3                       1020
#define IDC_COMBO1                      1020
#define SP_MINDIM                       1020
#define CB_CONTENT                      1020
#define IDC_SPIN2                       1021
#define SP_MAXDIM                       1021
#define IDC_EDIT4                       1022
#define SP_MINPOLYS                     1022
#define IDC_SPIN3                       1023
#define IDC_EDIT7                       1023
#define IDC_EDIT5                       1024
#define IDC_EDIT8                       1024
#define IDC_SPIN4                       1025
#define IDC_EDIT6                       1026
#define IDC_SPIN5                       1027
#define CB_SUBSTANCE                    1030
#define IDC_CHECK5                      1032
#define EF_FOGGY                        1032
#define CK_FOGGY                        1032
#define IDC_CHECK6                      1033
#define CK_SAVEIMG                      1033
#define IDC_CHECK12                     1034
#define CK_SAVESND                      1034
#define CK_SHELL                        1037
#define IDC_EDIT1                       1038
#define EF_MINDIM                       1039
#define RB_SOLID                        1040
#define EF_MAXDIM                       1040
#define RB_CUT                          1041
#define EF_MINPOLYS                     1041
#define CK_SPLITABLE                    1042
#define CK_REVERSE                      1043
#define IDC_STATICT                     1044
#define IDC_STATICRS                    1045
#define IDC_STATICVS                    1046
#define RB_CUTALL                       1047
#define IDC_STATICX                     1052
#define TAB_DLGS                        1055
#define ST_PLTEX                        1056
#define EF_OUT                          1058
#define IDC_BUTTON2                     1059
#define PB_ROTATE                       1059
#define PB_COLOR                        1061
#define PB_FLIPH                        1061
#define EF_ALPHA                        1062
#define PB_FLIPV                        1062
#define IDC_CHECK9                      1065
#define CK_TEXANIM                      1065
#define IDC_CHECK11                     1066
#define EF_SPEED                        1067
#define PB_APPLY                        1068
#define IDC_CHECK4                      1070
#define EF_FULLBRIGHT                   1070
#define CK_SAVEPORTALS                  1070
#define IDC_COMBO2                      1071
#define CB_DYNAMIC                      1071
#define IDC_CHECK7                      1072
#define IDC_BUTTON3                     1072
#define EF_HALLO                        1072
#define CK_HALLO                        1072
#define CK_SAVESKYDOM                   1072
#define RB_LINEAR                       1073
#define RB_CYLINDRIC                    1074
#define RB_SPHERIC                      1075
#define IDC_STATIC1                     1077
#define IDC_STATIC2                     1078
#define IDC_STATIC3                     1079
#define CK_CUT                          1080
#define CK_CUTALL                       1081
#define CK_DETAIL                       1082
#define CK_NOCOLL                       1083
#define CK_DYNAMIC                      1084
#define RB_SHIFT                        1086
#define CK_SKY                          1087
#define IDC_STATICTA                    1088
#define PB_CANCEL                       1089
#define CK_DETDETBRUSH                  1090
#define PB_CLEAR                        1091
#define CK_DETDETBRUSH2                 1092
#define PB_FILE                         1093
#define EF_FILENAME                     1094
#define PB_MORE                         1095
#define RB_PVS                          1096
#define RB_FULLPVS                      1097
#define IDC_STATICA                     1098
#define IDC_LIST2                       1099
#define PB_SELTBT                       1100
#define IDC_STATICMAT                   1101
#define CK_INGNORE                      1102
#define LB_SCPROPS                      1108
#define ID_TB_LOCKXYZ                   22771
#define ID_BUROTATE                     22773
#define ID_BUMOVE                       22774
#define ID_BUScale                      22775
#define ID_BUSHCAM                      22776
#define ID_BUSNAPGRID                   22777
#define ID_BUREVERSE                    22778
#define ID_BUTSELBRUSH                  22782
#define ID_BUFACESEL                    22783
#define ID_BUTTON22784                  22784
#define ID_BUVXSEL                      22785
#define ID_BUCYL                        22786
#define ID_BUARCH                       22787
#define ID_BUCONE                       22788
#define ID_BUSTAIRS                     22789
#define ID_BULIGTH                      22790
#define ID_BUWIREFRAME                  22791
#define ID_BUSHOWBACK                   22792
#define ID_BUCSG                        22793
#define ID_BUSHOWDLG                    22794
#define ID_BUSHOWCSG                    22796
#define ID_BUTINV                       22797
#define ID_MK_BOXHOLLOW                 22798
#define ID_DELETE                       22799
#define ID_CUT                          22800
#define ID_TAB_NEXTSEL                  22801
#define SB_COORD                        22802
#define ID_MK_BOX                       22803
#define SB_MOUSECOORD                   22804
#define ID_MK_ROOM                      22805
#define IDS_POLYSCNT                    22806
#define ID_BUSHEET                      22808
#define ID_BURISELOW                    22809
#define MN_PROPS                        22812
#define MN_GLOBALS                      22815
#define MN_ESCAPE                       22816
#define MN_CUT                          22817
#define MN_MIRROR                       22818
#define MN_ENTER                        22819
#define ID_BUALIGN                      22820
#define TBB_XALIGN                      22823
#define TBB_YALIGN                      22824
#define TBB_ZALIGN                      22825
#define TBB_XINTER                      22828
#define TBB_YINTER                      22829
#define TBB_ZINTER                      22830
#define TBB_XDIM                        22831
#define TBB_YDIM                        22832
#define TBB_ZDIM                        22833
#define TBB_XYZDIM                      22834
#define MN_APLLYTEX                     22836
#define IDS_BOXDIM                      22837
#define ID_BUSPLITABLE                  22837
#define ID_BUTTON22838                  22838
#define ID_TAB_PREVSEL                  22840
#define ID_SELECTALL                    22841
#define ID_TAB_SELNEXT                  22842
#define ID_TAB_SELPREV                  22843
#define ID_COMPBSP                      22844
#define ID_DELFACE                      22845
#define ID_BUCOMPILE                    22846
#define ID_BUVIEWBSP                    22847
#define ID_BUVIEWTGRAPH                 22848
#define ID_SELSAMEASSELFACE             22851
#define ID_ALIGH_BOTHIT                 22852
#define ID_ALIGH_TOPHIT                 22853
#define ID_ALIGN_RIGHT_HIT              22854
#define ID_ALIGH_LEFTHIT                22855
#define ID_BUSPHERE                     22856
#define SB_CAMPOS                       22857
#define MN_YOY                          22857
#define SB_2DPOS                        22858
#define ID_EDIT_MIRROR_XOZ              22858
#define SB_BRUSHBBOX                    22859
#define ID_EDIT_MIRROR_ZOX              22859
#define SB_MOUSEPOS                     22860
#define MN_SELVERTEX                    22862
#define ID_SETTINGS_PREFERENCES         22874
#define MN_SELECTGROUP                  22876
#define MN_SELCURID                     22877
#define TBB_LR                          22878
#define TBB_TB                          22879
#define TBB_FB                          22880
#define ID_BUTTON22881                  22881
#define ID_CTX2D_ROTATECW_30            22882
#define ID_CTX2D_ROTATECW_60            22883
#define ID_CTX2D_ROTATECW_90            22884
#define ID_CTX2D_ROTATECW_45            22885
#define MN_HELP                         22886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        164
#define _APS_NEXT_COMMAND_VALUE         22887
#define _APS_NEXT_CONTROL_VALUE         1109
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
