// auto-generated include file
case WDS_ICON_ampersnd:
return wdsXPMampersnd;
case WDS_ICON_angry:
return wdsXPMangry;
case WDS_ICON_approx:
return wdsXPMapprox;
case WDS_ICON_asterisk:
return wdsXPMasterisk;
case WDS_ICON_away0:
return wdsXPMaway0;
case WDS_ICON_away1:
return wdsXPMaway1;
case WDS_ICON_biohaz:
return wdsXPMbiohaz;
case WDS_ICON_blank:
return wdsXPMblank;
case WDS_ICON_block:
return wdsXPMblock;
case WDS_ICON_bold:
return wdsXPMbold;
case WDS_ICON_bug:
return wdsXPMbug;
case WDS_ICON_bulb:
return wdsXPMbulb;
case WDS_ICON_check:
return wdsXPMcheck;
case WDS_ICON_chevron:
return wdsXPMchevron;
case WDS_ICON_circle:
return wdsXPMcircle;
case WDS_ICON_cross:
return wdsXPMcross;
case WDS_ICON_crosshr:
return wdsXPMcrosshr;
case WDS_ICON_cycle:
return wdsXPMcycle;
case WDS_ICON_delta:
return wdsXPMdelta;
case WDS_ICON_dline0:
return wdsXPMdline0;
case WDS_ICON_dline1:
return wdsXPMdline1;
case WDS_ICON_dline2:
return wdsXPMdline2;
case WDS_ICON_dline3:
return wdsXPMdline3;
case WDS_ICON_dollar:
return wdsXPMdollar;
case WDS_ICON_dot:
return wdsXPMdot;
case WDS_ICON_eject:
return wdsXPMeject;
case WDS_ICON_ex0:
return wdsXPMex0;
case WDS_ICON_ex1:
return wdsXPMex1;
case WDS_ICON_ex2:
return wdsXPMex2;
case WDS_ICON_ex3:
return wdsXPMex3;
case WDS_ICON_exclam:
return wdsXPMexclam;
case WDS_ICON_explode:
return wdsXPMexplode;
case WDS_ICON_file:
return wdsXPMfile;
case WDS_ICON_flash0:
return wdsXPMflash0;
case WDS_ICON_forbid:
return wdsXPMforbid;
case WDS_ICON_happy:
return wdsXPMhappy;
case WDS_ICON_home:
return wdsXPMhome;
case WDS_ICON_imi:
return wdsXPMimi;
case WDS_ICON_in:
return wdsXPMin;
case WDS_ICON_infinity:
return wdsXPMinfinity;
case WDS_ICON_insect:
return wdsXPMinsect;
case WDS_ICON_italic:
return wdsXPMitalic;
case WDS_ICON_join:
return wdsXPMjoin;
case WDS_ICON_layer:
return wdsXPMlayer;
case WDS_ICON_lightng:
return wdsXPMlightng;
case WDS_ICON_line0:
return wdsXPMline0;
case WDS_ICON_line1:
return wdsXPMline1;
case WDS_ICON_line2:
return wdsXPMline2;
case WDS_ICON_line3:
return wdsXPMline3;
case WDS_ICON_lock:
return wdsXPMlock;
case WDS_ICON_mail:
return wdsXPMmail;
case WDS_ICON_man:
return wdsXPMman;
case WDS_ICON_out:
return wdsXPMout;
case WDS_ICON_paper:
return wdsXPMpaper;
case WDS_ICON_paragrph:
return wdsXPMparagrph;
case WDS_ICON_pencil0:
return wdsXPMpencil0;
case WDS_ICON_pencil1:
return wdsXPMpencil1;
case WDS_ICON_percent:
return wdsXPMpercent;
case WDS_ICON_phone:
return wdsXPMphone;
case WDS_ICON_plus0:
return wdsXPMplus0;
case WDS_ICON_plus1:
return wdsXPMplus1;
case WDS_ICON_plus2:
return wdsXPMplus2;
case WDS_ICON_plus3:
return wdsXPMplus3;
case WDS_ICON_poison:
return wdsXPMpoison;
case WDS_ICON_pound:
return wdsXPMpound;
case WDS_ICON_printer:
return wdsXPMprinter;
case WDS_ICON_pull:
return wdsXPMpull;
case WDS_ICON_question:
return wdsXPMquestion;
case WDS_ICON_radhaz:
return wdsXPMradhaz;
case WDS_ICON_ramp:
return wdsXPMramp;
case WDS_ICON_rcircle:
return wdsXPMrcircle;
case WDS_ICON_recycle:
return wdsXPMrecycle;
case WDS_ICON_sad:
return wdsXPMsad;
case WDS_ICON_scissors:
return wdsXPMscissors;
case WDS_ICON_search:
return wdsXPMsearch;
case WDS_ICON_slash0:
return wdsXPMslash0;
case WDS_ICON_slash1:
return wdsXPMslash1;
case WDS_ICON_slash2:
return wdsXPMslash2;
case WDS_ICON_slash3:
return wdsXPMslash3;
case WDS_ICON_sonic:
return wdsXPMsonic;
case WDS_ICON_sort:
return wdsXPMsort;
case WDS_ICON_square:
return wdsXPMsquare;
case WDS_ICON_squeeze:
return wdsXPMsqueeze;
case WDS_ICON_star:
return wdsXPMstar;
case WDS_ICON_step:
return wdsXPMstep;
case WDS_ICON_sun0:
return wdsXPMsun0;
case WDS_ICON_sun1:
return wdsXPMsun1;
case WDS_ICON_target:
return wdsXPMtarget;
case WDS_ICON_ticket:
return wdsXPMticket;
case WDS_ICON_tilde:
return wdsXPMtilde;
case WDS_ICON_tline0:
return wdsXPMtline0;
case WDS_ICON_tline1:
return wdsXPMtline1;
case WDS_ICON_tline2:
return wdsXPMtline2;
case WDS_ICON_translat:
return wdsXPMtranslat;
case WDS_ICON_undrline:
return wdsXPMundrline;
case WDS_ICON_unlock:
return wdsXPMunlock;
case WDS_ICON_up0:
return wdsXPMup0;
case WDS_ICON_up1:
return wdsXPMup1;
case WDS_ICON_up2:
return wdsXPMup2;
case WDS_ICON_up3:
return wdsXPMup3;
case WDS_ICON_woman:
return wdsXPMwoman;
