CC = g++ -Wall -ansi

all:
	$(CC) -c ../../../source/Socket.cpp -I /usr/include -I ../../../source
	$(CC) -c ../../../source/Network.cpp -I /usr/include -I ../../../source

clean:
	@echo Cleaning up...
	@rm Socket
	@rm Network
	@echo Done.
