#ifndef SGXDRV_WINTEL32_CORE_THREADING_THREADING_HPP
#define SGXDRV_WINTEL32_CORE_THREADING_THREADING_HPP	1

#include "drivers/wintel32/core/threading/wintel32threadmanager.hpp"


#endif /* SGXDRV_WINTEL32_CORE_THREADING_THREADING_HPP */

