/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ptc_jni_Copy */

#ifndef _Included_ptc_jni_Copy
#define _Included_ptc_jni_Copy
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ptc_jni_Copy
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ptc_jni_Copy_create
  (JNIEnv *, jobject);

/*
 * Class:     ptc_jni_Copy
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Copy_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Copy
 * Method:    request
 * Signature: (JLptc/Format;Lptc/Format;)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Copy_request
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ptc_jni_Copy
 * Method:    palette
 * Signature: (JLptc/Palette;Lptc/Palette;)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Copy_palette
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ptc_jni_Copy
 * Method:    copy
 * Signature: (JLjava/lang/Object;IIIIILjava/lang/Object;IIIII)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Copy_copy
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jint, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     ptc_jni_Copy
 * Method:    option
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ptc_jni_Copy_option
  (JNIEnv *, jobject, jlong, jstring);

#ifdef __cplusplus
}
#endif
#endif
