/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ptc_jni_Timer */

#ifndef _Included_ptc_jni_Timer
#define _Included_ptc_jni_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ptc_jni_Timer
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ptc_jni_Timer_create
  (JNIEnv *, jobject);

/*
 * Class:     ptc_jni_Timer
 * Method:    destroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Timer_destroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Timer
 * Method:    set
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Timer_set
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     ptc_jni_Timer
 * Method:    start
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Timer_start
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Timer
 * Method:    stop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ptc_jni_Timer_stop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Timer
 * Method:    time
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ptc_jni_Timer_time
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Timer
 * Method:    delta
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ptc_jni_Timer_delta
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ptc_jni_Timer
 * Method:    resolution
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_ptc_jni_Timer_resolution
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
