//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by MSLEdit.rc
//
#define IDD_DIALOG1                     101
#define IDD_EDIT                        101
#define IDD_MODIFY                      102
#define IDC_LOAD                        1000
#define IDC_SAVE                        1001
#define IDC_CHARACTERS                  1002
#define IDC_NEW                         1003
#define IDC_OK                          1004
#define IDC_NUM                         1005
#define IDC_WEAPON                      1006
#define IDC_ARMOR                       1007
#define IDC_SHIELD                      1008
#define IDC_HEALING                     1009
#define IDC_CONTAINER                   1010
#define IDC_MONEY                       1011
#define IDC_ACCESSORY                   1012
#define IDC_EDIBLE                      1013
#define IDC_COLLECTION                  1014
#define IDC_TRANSPORTATION              1015
#define IDC_SELLABLE                    1016
#define IDC_CANDROP                     1017
#define IDC_USEONCE                     1018
#define IDC_UNKNOWN                     1019
#define IDC_SPELLS                      1020
#define IDC_NAME                        1021
#define IDC_DESCRIPTION                 1022
#define IDC_SETALL                      1023
#define IDC_NAME2                       1023
#define IDC_MESH1                       1023
#define IDC_WEIGHT                      1024
#define IDC_NAME3                       1024
#define IDC_SCRIPT                      1024
#define IDC_NAME4                       1025
#define IDC_SPEED1                      1025
#define IDC_VALUE                       1026
#define IDC_RADIO2                      1026
#define IDC_HEALTH                      1026
#define IDC_PRICE                       1027
#define IDC_RADIO3                      1027
#define IDC_MANA                        1027
#define IDC_CLEARALL                    1028
#define IDC_RADIO4                      1028
#define IDC_CURE                        1028
#define IDC_RADIO5                      1029
#define IDC_CAUSE                       1029
#define IDC_ITEM                        1030
#define IDC_RADIO6                      1030
#define IDC_MESH                        1031
#define IDC_RADIO7                      1031
#define IDC_KILL                        1031
#define IDC_CANCEL                      1032
#define IDC_ATTACK                      1033
#define IDC_RADIO11                     1033
#define IDC_NOTHING                     1033
#define IDC_DEFENSE                     1034
#define IDC_RADIO8                      1034
#define IDC_SINGLE                      1034
#define IDC_AGILITY                     1035
#define IDC_RADIO9                      1035
#define IDC_AREA                        1035
#define IDC_RADIO12                     1036
#define IDC_ABILITY                     1036
#define IDC_RADIO10                     1037
#define IDC_SELF                        1037
#define IDC_RADIO15                     1038
#define IDC_GROUP                       1038
#define IDC_RADIO16                     1039
#define IDC_CASTER1                     1039
#define IDC_RADIO13                     1040
#define IDC_DISPEL                      1040
#define IDC_RADIO14                     1041
#define IDC_TELEPORT                    1041
#define IDC_RADIO17                     1042
#define IDC_TOTARGET1                   1042
#define IDC_RADIO18                     1043
#define IDC_TOCASTER1                   1043
#define IDC_RADIO19                     1044
#define IDC_TARGET1                     1044
#define IDC_NAME5                       1045
#define IDC_SOUND                       1045
#define IDC_SOUND1                      1045
#define IDC_NAME6                       1046
#define IDC_MESH2                       1046
#define IDC_DROPITEM                    1047
#define IDC_RADIO20                     1047
#define IDC_CASTER2                     1047
#define IDC_TODROP                      1048
#define IDC_RADIO21                     1048
#define IDC_TOTARGET2                   1048
#define IDC_CHARGE                      1049
#define IDC_DMGCLASS                    1049
#define IDC_CHARGE2                     1050
#define IDC_CHANCE                      1050
#define IDC_SPEED                       1051
#define IDC_CHARGE3                     1051
#define IDC_VALUE1                      1051
#define IDC_TOATTACK                    1052
#define IDC_CHARGE4                     1052
#define IDC_COST                        1052
#define IDC_TOMAGIC                     1053
#define IDC_CHARGE5                     1053
#define IDC_RANGE                       1053
#define IDC_CHARGE6                     1054
#define IDC_VALUE2                      1054
#define IDC_EFFECT                      1055
#define IDC_RADIO22                     1055
#define IDC_TOCASTER2                   1055
#define IDC_EDIT                        1056
#define IDC_RADIO23                     1056
#define IDC_TARGET2                     1056
#define IDC_CLEAR                       1057
#define IDC_NAME7                       1057
#define IDC_SPEED2                      1057
#define IDC_NAME8                       1058
#define IDC_MESH3                       1058
#define IDC_RADIO24                     1059
#define IDC_CASTER3                     1059
#define IDC_RADIO25                     1060
#define IDC_TOTARGET3                   1060
#define IDC_RADIO26                     1061
#define IDC_TOCASTER3                   1061
#define IDC_RADIO27                     1062
#define IDC_TARGET3                     1062
#define IDC_NAME9                       1063
#define IDC_SPEED3                      1063
#define IDC_VALUE3                      1064
#define IDC_CURECLASS                   1065
#define IDC_SOUND2                      1066
#define IDC_SOUND3                      1067
#define IDC_RAISE                       1068
#define IDC_NONE1                       1069
#define IDC_NONE2                       1070
#define IDC_NONE3                       1071
#define IDC_VALUE4                      1072
#define IDC_DISTANCE                    1073
#define IDC_SCALE1                      1074
#define IDC_SCALE2                      1075
#define IDC_SCALE3                      1076
#define IDC_LOOP1                       1077
#define IDC_LOOP2                       1078
#define IDC_LOOP3                       1079

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1078
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
