// auto-generated include file
#define WDS_ICON_ampersnd 1
#define WDS_ICON_angry 2
#define WDS_ICON_approx 3
#define WDS_ICON_asterisk 4
#define WDS_ICON_away0 5
#define WDS_ICON_away1 6
#define WDS_ICON_biohaz 7
#define WDS_ICON_blank 8
#define WDS_ICON_block 9
#define WDS_ICON_bold 10
#define WDS_ICON_bug 11
#define WDS_ICON_bulb 12
#define WDS_ICON_check 13
#define WDS_ICON_chevron 14
#define WDS_ICON_circle 15
#define WDS_ICON_cross 16
#define WDS_ICON_crosshr 17
#define WDS_ICON_cycle 18
#define WDS_ICON_delta 19
#define WDS_ICON_dline0 20
#define WDS_ICON_dline1 21
#define WDS_ICON_dline2 22
#define WDS_ICON_dline3 23
#define WDS_ICON_dollar 24
#define WDS_ICON_dot 25
#define WDS_ICON_eject 26
#define WDS_ICON_ex0 27
#define WDS_ICON_ex1 28
#define WDS_ICON_ex2 29
#define WDS_ICON_ex3 30
#define WDS_ICON_exclam 31
#define WDS_ICON_explode 32
#define WDS_ICON_file 33
#define WDS_ICON_flash0 34
#define WDS_ICON_forbid 35
#define WDS_ICON_happy 36
#define WDS_ICON_home 37
#define WDS_ICON_imi 38
#define WDS_ICON_in 39
#define WDS_ICON_infinity 40
#define WDS_ICON_insect 41
#define WDS_ICON_italic 42
#define WDS_ICON_join 43
#define WDS_ICON_layer 44
#define WDS_ICON_lightng 45
#define WDS_ICON_line0 46
#define WDS_ICON_line1 47
#define WDS_ICON_line2 48
#define WDS_ICON_line3 49
#define WDS_ICON_lock 50
#define WDS_ICON_mail 51
#define WDS_ICON_man 52
#define WDS_ICON_out 53
#define WDS_ICON_paper 54
#define WDS_ICON_paragrph 55
#define WDS_ICON_pencil0 56
#define WDS_ICON_pencil1 57
#define WDS_ICON_percent 58
#define WDS_ICON_phone 59
#define WDS_ICON_plus0 60
#define WDS_ICON_plus1 61
#define WDS_ICON_plus2 62
#define WDS_ICON_plus3 63
#define WDS_ICON_poison 64
#define WDS_ICON_pound 65
#define WDS_ICON_printer 66
#define WDS_ICON_pull 67
#define WDS_ICON_question 68
#define WDS_ICON_radhaz 69
#define WDS_ICON_ramp 70
#define WDS_ICON_rcircle 71
#define WDS_ICON_recycle 72
#define WDS_ICON_sad 73
#define WDS_ICON_scissors 74
#define WDS_ICON_search 75
#define WDS_ICON_slash0 76
#define WDS_ICON_slash1 77
#define WDS_ICON_slash2 78
#define WDS_ICON_slash3 79
#define WDS_ICON_sonic 80
#define WDS_ICON_sort 81
#define WDS_ICON_square 82
#define WDS_ICON_squeeze 83
#define WDS_ICON_star 84
#define WDS_ICON_step 85
#define WDS_ICON_sun0 86
#define WDS_ICON_sun1 87
#define WDS_ICON_target 88
#define WDS_ICON_ticket 89
#define WDS_ICON_tilde 90
#define WDS_ICON_tline0 91
#define WDS_ICON_tline1 92
#define WDS_ICON_tline2 93
#define WDS_ICON_translat 94
#define WDS_ICON_undrline 95
#define WDS_ICON_unlock 96
#define WDS_ICON_up0 97
#define WDS_ICON_up1 98
#define WDS_ICON_up2 99
#define WDS_ICON_up3 100
#define WDS_ICON_woman 101
