//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by menu.rc
//
#define IDR_TOOLBAR                     111
#define IDC_EDIT                        1002
#define IDC_NAME                        1004
#define IDC_POLYS                       1005
#define IDC_VERTS                       1006
#define IDC_INDIS                       1007
#define IDC_PORTS                       1008
#define IDC_MESHS                       1009
#define IDC_LIGHTS                      1010
#define IDC_SECNAME                     1011
#define IDC_VINP                        1011
#define IDC_SECTORS                     1011
#define IDC_IINP                        1012
#define IDC_VINM                        1013
#define IDC_IINM                        1014
#define IDC_PINM                        1015
#define IDC_ENTITIES                    1016
#define IDC_WIDTH                       1020
#define IDC_SET_WIDTH                   1021
#define IDC_HEIGHT                      1022
#define IDC_SET_HEIGHT                  1023
#define IDC_DEPTH                       1024
#define IDC_SET_DEPTH                   1025
#define IDC_POSX                        1026
#define IDC_POSY                        1027
#define IDC_POSZ                        1028
#define IDC_INVERTED                    1029
#define IDC_SCROLLU                     1037
#define IDC_OFFV                        1038
#define IDC_OFFU                        1039
#define IDC_SCROLLV                     1040
#define IDC_REPU_M                      1041
#define IDC_REPV_M                      1042
#define IDC_REPU                        1043
#define IDC_REPV                        1044
#define IDC_REPU_P                      1045
#define IDC_REPV_P                      1046
#define IDC_LIST                        1046
#define IDC_TEXTURE                     1047
#define IDC_BUMP                        1048
#define IDC_DETAIL                      1049
#define IDC_ASBUMP                      1052
#define IDC_ASDETAIL                    1053
#define IDC_CLEAR                       1054
#define IDC_RED                         1055
#define IDC_GREEN                       1056
#define IDC_R                           1056
#define IDC_BLUE                        1057
#define IDC_G                           1057
#define IDC_B                           1058
#define IDC_RAD                         1059
#define IDC_POS                         1060
#define IDC__SLIDEDOOR                  1063
#define IDC_SLIDEDOOR                   1063
#define IDC__BOT                        1064
#define IDC_UNUSED2                     1064
#define IDC_XAXIS                       1064
#define IDC_UNUSED1                     1065
#define IDC_YAXIS                       1065
#define IDC_UNUSED3                     1066
#define IDC_ZAXIS                       1066
#define IDC_DIST                        1067
#define IDC_PAUSE                       1068
#define IDC_FLICKER                     1068
#define IDC_X                           1069
#define IDC_SHADOW                      1069
#define IDC_Y                           1070
#define IDC_Z                           1071
#define IDC_DEG                         1072
#define IDC_AMB_R                       1073
#define IDC_AMB_G                       1074
#define IDC_AMB_B                       1075
#define IDC_AMB_A                       1076
#define IDC_DIF_R                       1077
#define IDC_DIF_G                       1078
#define IDC_DIF_B                       1079
#define IDC_DIF_A                       1080
#define IDC_EMI_R                       1081
#define IDC_EMI_G                       1082
#define IDC_EMI_B                       1083
#define IDC_EMI_A                       1084
#define IDC_SPE_R                       1085
#define IDC_SPE_G                       1086
#define IDC_SPE_B                       1087
#define IDC_SPE_A                       1088
#define IDC_SPE_P                       1089
#define IDM_FILE_OPEN                   40002
#define IDM_FILE_NEW                    40003
#define IDM_FILE_SAVE                   40004
#define IDM_FILE_SAVE_AS                40005
#define IDM_FILE_QUIT                   40006
#define IDM_FILE_EXIT                   40006
#define IDM_HELP_INDEX                  40007
#define IDM_HELP_INFO                   40008
#define IDM_INSERT_MODELL               40009
#define IDM_INSERT_LIGHT                40010
#define IDTB_TEST1                      40011
#define IDTB_FILE_OPEN                  40017
#define IDTB_FILE_SAVE                  40018
#define IDTB_FILE_NEW                   40019
#define IDTB_INSERT_SHAPE_CUBE          40020
#define IDTB_LIGHT_EDIT                 40021
#define IDTB_INSERT_ENTITY              40022
#define IDTB_SECTOR_NEW                 40023
#define IDTB_SECTOR_DELETE              40024
#define IDTB_SECTOR_ATTRIBUTES          40026
#define IDTB_INSERT_LIGHT               40028
#define IDM_EDIT_MERGE                  40029
#define IDM_EDIT_FRAGMENT               40031
#define IDM_EDIT_INSERTCOPY             40032
#define IDM_EDIT_DELETE                 40034
#define IDM_EDIT_SELECTALL              40035
#define IDM_PORTS_GRID3D                40036
#define IDM_PORTS_VERTS3D               40037
#define IDM_PORTS_VERTS                 40038
#define IDM_PORTS_WIRE3D                40039
#define IDM_PORTS_WIRE                  40040
#define IDM_PORTS_GRID                  40041
#define IDTB_INSERT_SHAPE_RECT          40042
#define IDTB_LEVEL_ATTRIBUTES           40043
#define IDTB_MAKE_PORTAL                40044
#define IDTB_PORTAL_CONNECT             40045
#define IDM_EDIT_INSIDEOUT              40046
#define IDTB_GEO_INSIDEOUT              40047
#define IDM_EDIT_SNAP                   40048
#define IDTB_INSERT_SHAPE_LIGHT         40049
#define IDM_CAM_TO_ORIG                 40051
#define IDM_CAM_TO_SEL                  40052
#define IDM_CAM_CENTER                  40053
#define IDTB_MESH_OPEN                  40054
#define IDTB_MESH_SAVE                  40055
#define IDM_EDIT_ROTA_X                 40057
#define IDM_EDIT_ROTA_Y                 40058
#define IDM_EDIT_ROTA_Z                 40059
#define IDM_PORTS_INACTIVE              40060
#define IDM_EDIT_SNAPVERTS              40062
#define IDTB_SECTOR_AMBIENT             40063
#define IDM_EDIT_MIRROR_X               40065
#define IDM_EDIT_MIRROR_Y               40066
#define IDM_EDIT_MIRROR_Z               40067
#define IDM_PORTS_LIGHT                 40068
#define IDM_PORTS_INACTIVE3D            40070
#define IDM_PORTS_INACTIVE3DW           40071
#define IDTB_MAKE_ENTITY                40072
#define IDTB_EDIT_ENTITY                40073
#define IDM_EDIT_ROTA_A                 40074
#define IDTB_EDIT_SPAWN                 40075
#define IDTB_INSERT_SPAWN               40076

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        125
#define _APS_NEXT_COMMAND_VALUE         40077
#define _APS_NEXT_CONTROL_VALUE         1090
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
