build :
	@mkdir -p OpenGL/Debug
	@mkdir -p OpenGL/Release
	make build_project -f makelib.lnx CONFIG=Debug
	make build_project -f makelib.lnx CONFIG=Release

clean :
	make clean_project -f makelib.lnx CONFIG=Debug
	make clean_project -f makelib.lnx CONFIG=Release

