//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by EnvAudioDemo.rc
//
#define IDI_MAIN_ICON                   101
#define IDR_MAIN_ACCEL                  113
#define IDR_MENU                        141
#define IDR_POPUP                       142
#define IDD_SELECTDEVICE                144
#define IDR_XFILE2                      149
#define IDC_DEVICE_COMBO                1000
#define IDC_ADAPTER_COMBO               1002
#define IDC_ADAPTERFORMAT_COMBO         1003
#define IDC_RESOLUTION_COMBO            1004
#define IDC_MULTISAMPLE_COMBO           1005
#define IDC_REFRESHRATE_COMBO           1006
#define IDC_BACKBUFFERFORMAT_COMBO      1007
#define IDC_DEPTHSTENCILBUFFERFORMAT_COMBO 1008
#define IDC_VERTEXPROCESSING_COMBO      1009
#define IDC_PRESENTINTERVAL_COMBO       1010
#define IDC_MULTISAMPLE_QUALITY_COMBO   1011
#define IDC_WINDOW                      1016
#define IDC_FULLSCREEN                  1018
#define IDC_COMBO1                      1027
#define IDM_TOGGLEFULLSCREEN            40003
#define IDM_EXIT                        40006
#define IDM_CONFIGINPUT                 40011
#define IDM_ENABLEZOOMFX                40012
#define ID_EAXENVIRONMENT_GENERIC       40013
#define ID_EAXENVIRONMENT_PADDEDCELL    40014
#define ID_EAXENVIRONMENT_ROOM          40015
#define ID_EAXENVIRONMENT_BATHROOM      40016
#define ID_EAXENVIRONMENT_LIVINGROOM    40017
#define ID_EAXENVIRONMENT_STONEROOM     40018
#define ID_EAXENVIRONMENT_AUDITORIUM    40019
#define ID_EAXENVIRONMENT_CONCERTHALL   40020
#define ID_EAXENVIRONMENT_CAVE          40021
#define ID_EAXENVIRONMENT_ARENA         40022
#define ID_EAXENVIRONMENT_HANGAR        40023
#define ID_EAXENVIRONMENT_CARPETEDHALLWAY 40024
#define ID_EAXENVIRONMENT_HALLWAY       40025
#define ID_EAXENVIRONMENT_STONECORRIDOR 40026
#define ID_EAXENVIRONMENT_ALLEY         40027
#define ID_EAXENVIRONMENT_FOREST        40028
#define ID_EAXENVIRONMENT_CITY          40029
#define ID_EAXENVIRONMENT_MOUNTAINS     40030
#define ID_EAXENVIRONMENT_QUARRY        40031
#define ID_EAXENVIRONMENT_PLAIN         40032
#define ID_EAXENVIRONMENT_PARKINGLOT    40033
#define ID_EAXENVIRONMENT_SEWERPIPE     40034
#define ID_EAXENVIRONMENT_UNDERWATER    40035
#define ID_EAXENVIRONMENT_DRUGGED       40036
#define ID_EAXENVIRONMENT_DIZZY         40037
#define ID_EAXENVIRONMENT_PSYCHOTIC     40038
#define ID_EAXENVIRONMENT_PRESETS       40039
#define ID_EAXENVIRONMENT_MANUALSETTING 40040
#define ID_FILE_OPENLEVEL               40041
#define IDM_CHANGEDEVICE                40045

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         40046
#define _APS_NEXT_CONTROL_VALUE         1028
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
