// Magic Software, Inc.
// http://www.magic-software.com
// http://www.wild-magic.com
// Copyright (c) 2004.  All Rights Reserved
//
// The Wild Magic Library (WM3) source code is supplied under the terms of
// the license agreement http://www.wild-magic.com/License/WildMagic3.pdf and
// may not be copied or disclosed except in accordance with the terms of that
// agreement.

#include "Wm3RefractionVShader.h"
using namespace Wm3;

WM3_IMPLEMENT_RTTI(Wm3,RefractionVShader,VertexShader);
WM3_IMPLEMENT_STREAM(RefractionVShader);
WM3_IMPLEMENT_DEFAULT_STREAM(RefractionVShader,VertexShader);
WM3_IMPLEMENT_DEFAULT_NAME_ID(RefractionVShader,VertexShader);

//----------------------------------------------------------------------------
RefractionVShader::RefractionVShader ()
{
    // shader program (load the type of the current renderer)
    m_acProgram = ms_aacProgram[Renderer::GetType()];

    // shader constants
    int iType, iOption, iReg, iRegQuantity;
    ShaderConstant* pkConst;

    // model-to-view * projection matrix (4x4)
    iType = ShaderConstant::SC_TRANSFORM_MVP;
    iOption = ShaderConstant::SCO_MATRIX;
    iReg = 0;
    iRegQuantity = 4;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // model-to-world matrix (4x4)
    iType = ShaderConstant::SC_TRANSFORM_M;
    iOption = ShaderConstant::SCO_MATRIX;
    iReg = 4;
    iRegQuantity = 4;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // camera position vector (x,y,z,1)
    iType = ShaderConstant::SC_CAMERA_POSITION;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 8;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // user defined vector (register 9)
    // IndexOfRefraction
    iType = ShaderConstant::SC_USER_DEFINED;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 9;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // user defined vector (register 10)
    // FresnelConstants
    iType = ShaderConstant::SC_USER_DEFINED;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 10;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // numerical constant vector (register 11)
    iType = ShaderConstant::SC_NUMERICAL_CONSTANT;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 11;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    pkConst->SetRegisterData(0,0.000000f,1.00000f,2.00000f,0.500000f);
    m_kConstant.Append(pkConst);

}
//----------------------------------------------------------------------------
RefractionVShader::~RefractionVShader ()
{
}
//----------------------------------------------------------------------------
const char* RefractionVShader::ms_aacProgram[Renderer::RT_QUANTITY] =
{
"!!ARBvp1.0\n"
"# ARB_vertex_program generated by NVIDIA Cg compiler\n"
"# cgc version 1.1.0003, build date Jul  7 2003  11:55:19\n"
"# command line args: -q -profile arbvp1 -entry vmain\n"
"# nv30vp backend compiling 'vmain' program\n"
"PARAM c11 = { 0, 1, 2, 0.5 };\n"
"#vendor NVIDIA Corporation\n"
"#version 1.0.02\n"
"#profile arbvp1\n"
"#program vmain\n"
"#semantic vmain.Wm3TransformMVP\n"
"#semantic vmain.Wm3TransformM\n"
"#semantic vmain.Wm3CameraPosition\n"
"#semantic vmain.IndexOfRefraction\n"
"#semantic vmain.FresnelConstants\n"
"#var float4 iPosition : $vin.POSITION : POSITION : 0 : 1\n"
"#var float4 iNormal : $vin.NORMAL : NORMAL : 1 : 1\n"
"#var float4 oPosition : $vout.POSITION : POSITION : 2 : 1\n"
"#var float4 oReflectFactor : $vout.COLOR : COLOR : 3 : 1\n"
"#var float2 oRefractVec : $vout.TEXCOORD0 : TEXCOORD0 : 4 : 1\n"
"#var float2 oReflectVec : $vout.TEXCOORD1 : TEXCOORD1 : 5 : 1\n"
"#var float4x4 Wm3TransformMVP :  : c[0], 4 : 6 : 1\n"
"#var float4x4 Wm3TransformM :  : c[4], 4 : 7 : 1\n"
"#var float4 Wm3CameraPosition :  : c[8] : 8 : 1\n"
"#var float IndexOfRefraction :  : c[9] : 9 : 1\n"
"#var float4 FresnelConstants :  : c[10] : 10 : 1\n"
"TEMP R0, R1, R2;\n"
"ATTRIB v18 = vertex.normal;\n"
"ATTRIB v16 = vertex.position;\n"
"PARAM c10 = program.local[10];\n"
"PARAM c9 = program.local[9];\n"
"PARAM c8 = program.local[8];\n"
"PARAM c4[4] = { program.local[4..7] };\n"
"PARAM c0[4] = { program.local[0..3] };\n"
"	DP4 result.position.x, c0[0], v16;\n"
"	DP4 result.position.y, c0[1], v16;\n"
"	DP4 result.position.z, c0[2], v16;\n"
"	DP4 result.position.w, c0[3], v16;\n"
"	DP3 R0.y, c4[0].xyzx, v18.xyzx;\n"
"	DP3 R0.z, c4[1].xyzx, v18.xyzx;\n"
"	DP3 R0.w, c4[2].xyzx, v18.xyzx;\n"
"	DP3 R0.x, R0.yzwy, R0.yzwy;\n"
"	RSQ R0.x, R0.x;\n"
"	MUL R1.xyz, R0.x, R0.yzwy;\n"
"	DP4 R0.x, c4[0], v16;\n"
"	DP4 R0.y, c4[1], v16;\n"
"	DP4 R0.z, c4[2], v16;\n"
"	ADD R0.yzw, R0.xxyz, -c8.xxyz;\n"
"	DP3 R0.x, R0.yzwy, R0.yzwy;\n"
"	RSQ R0.x, R0.x;\n"
"	MUL R0.xyz, R0.x, R0.yzwy;\n"
"	DP3 R0.w, R1.xyzx, R0.xyzx;\n"
"	MUL R2.xyz, c11.z, R1.xyzx;\n"
"	MAD R2.xyz, -R2.xyzx, R0.w, R0.xyzx;\n"
"	DP3 R0.w, R2.xyzx, R2.xyzx;\n"
"	RSQ R0.w, R0.w;\n"
"	MUL R2.yz, R0.w, R2.xyzx;\n"
"	MAD result.texcoord[1].xy, c11.w, R2.yzyy, c11.w;\n"
"	DP3 R2.x, -R0.xyzx, R1.xyzx;\n"
"	MAD R1.w, -R2.x, R2.x, c11.y;\n"
"	MUL R0.w, c9.x, c9.x;\n"
"	MAD R1.w, -R0.w, R1.w, c11.y;\n"
"	MAX R0.w, R1.w, -R1.w;\n"
"	RSQ R0.w, R0.w;\n"
"	RCP R0.w, R0.w;\n"
"	MAD R0.w, c9.x, R2.x, -R0.w;\n"
"	MUL R2.xyz, R0.w, R1.xyzx;\n"
"	MAD R2.xyz, c9.x, R0.xyzx, R2.xyzx;\n"
"	SLT R0.w, c11.x, R1.w;\n"
"	MUL R2.xyz, R2.xyzx, R0.w;\n"
"	DP3 R0.w, R2.xyzx, R2.xyzx;\n"
"	RSQ R0.w, R0.w;\n"
"	MUL R2.yz, R0.w, R2.xyzx;\n"
"	MAD result.texcoord[0].xy, c11.w, R2.yzyy, c11.w;\n"
"	DP3 R0.x, R0.xyzx, R1.xyzx;\n"
"	ADD R0.xy, c11.y, R0.x;\n"
"	MOV R0.zw, c10.z;\n"
"	LIT R0.z, R0;\n"
"	MAD result.color.front.primary.x, c10.y, R0.z, c10.x;\n"
"END\n"
"# 46 instructions\n"
"# 3 temp registers\n"
"# End of program\n"
,
"vs_1_1\n"
"// DX9 Vertex shader generated by NVIDIA Cg compiler\n"
"// cgc version 1.1.0003, build date Jul  7 2003  11:55:19\n"
"// command line args: -q -profile vs_1_1 -entry vmain -profileopts dcls -strict\n"
"// nv30vp backend compiling 'vmain' program\n"
"def c11, 0, 1, 2, 0.5\n"
"//vendor NVIDIA Corporation\n"
"//version 1.0.02\n"
"//profile vs_1_1\n"
"//program vmain\n"
"//semantic vmain.Wm3TransformMVP\n"
"//semantic vmain.Wm3TransformM\n"
"//semantic vmain.Wm3CameraPosition\n"
"//semantic vmain.IndexOfRefraction\n"
"//semantic vmain.FresnelConstants\n"
"//var float4 iPosition : $vin.POSITION : POSITION : 0 : 1\n"
"//var float4 iNormal : $vin.NORMAL : NORMAL : 1 : 1\n"
"//var float4 oPosition : $vout.POSITION : POSITION : 2 : 1\n"
"//var float4 oReflectFactor : $vout.COLOR : COLOR : 3 : 1\n"
"//var float2 oRefractVec : $vout.TEXCOORD0 : TEXCOORD0 : 4 : 1\n"
"//var float2 oReflectVec : $vout.TEXCOORD1 : TEXCOORD1 : 5 : 1\n"
"//var float4x4 Wm3TransformMVP :  : c[0], 4 : 6 : 1\n"
"//var float4x4 Wm3TransformM :  : c[4], 4 : 7 : 1\n"
"//var float4 Wm3CameraPosition :  : c[8] : 8 : 1\n"
"//var float IndexOfRefraction :  : c[9] : 9 : 1\n"
"//var float4 FresnelConstants :  : c[10] : 10 : 1\n"
"//const c[11] = 0 1 2 0.5\n"
"dcl_normal v3\n"
"dcl_position v0\n"
"	dp4 oPos.x, c0, v0\n"
"	dp4 oPos.y, c1, v0\n"
"	dp4 oPos.z, c2, v0\n"
"	dp4 oPos.w, c3, v0\n"
"	dp3 r0.y, c4.xyz, v3.xyz\n"
"	dp3 r0.z, c5.xyz, v3.xyz\n"
"	dp3 r0.w, c6.xyz, v3.xyz\n"
"	dp3 r0.x, r0.yzw, r0.yzw\n"
"	rsq r0.x, r0.x\n"
"	mul r1.xyz, r0.x, r0.yzw\n"
"	dp4 r0.x, c4, v0\n"
"	dp4 r0.y, c5, v0\n"
"	dp4 r0.z, c6, v0\n"
"	add r0.yzw, r0.xxyz, -c8.xxyz\n"
"	dp3 r0.x, r0.yzw, r0.yzw\n"
"	rsq r0.x, r0.x\n"
"	mul r0.xyz, r0.x, r0.yzw\n"
"	dp3 r0.w, r1.xyz, r0.xyz\n"
"	mul r2.xyz, c11.z, r1.xyz\n"
"	mad r2.xyz, -r2.xyz, r0.w, r0.xyz\n"
"	dp3 r0.w, r2.xyz, r2.xyz\n"
"	rsq r0.w, r0.w\n"
"	mul r2.yz, r0.w, r2.xyz\n"
"	mad oT1.xy, c11.w, r2.yz, c11.w\n"
"	dp3 r2.x, -r0.xyz, r1.xyz\n"
"	mad r1.w, -r2.x, r2.x, c11.y\n"
"	mul r0.w, c9.x, c9.x\n"
"	mad r1.w, -r0.w, r1.w, c11.y\n"
"	max r0.w, r1.w, -r1.w\n"
"	rsq r0.w, r0.w\n"
"	rcp r0.w, r0.w\n"
"	mad r0.w, c9.x, r2.x, -r0.w\n"
"	mul r2.xyz, r0.w, r1.xyz\n"
"	mad r2.xyz, c9.x, r0.xyz, r2.xyz\n"
"	slt r0.w, c11.x, r1.w\n"
"	mul r2.xyz, r2.xyz, r0.w\n"
"	dp3 r0.w, r2.xyz, r2.xyz\n"
"	rsq r0.w, r0.w\n"
"	mul r2.yz, r0.w, r2.xyz\n"
"	mad oT0.xy, c11.w, r2.yz, c11.w\n"
"	dp3 r0.x, r0.xyz, r1.xyz\n"
"	add r0.xy, c11.y, r0.x\n"
"	mov r0.zw, c10.z\n"
"	lit r0.z, r0\n"
"	mad oD0.x, c10.y, r0.z, c10.x\n"
"// 46 instructions\n"
"// 3 temp registers\n"
"// End of program\n"
};
