/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef ADVANCED2D_PRIVATE_H
#define ADVANCED2D_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.1.1.615"
#define VER_MAJOR	1
#define VER_MINOR	1
#define VER_RELEASE	1
#define VER_BUILD	615
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"Advanced2D Engine"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	""

#endif /*ADVANCED2D_PRIVATE_H*/
