/* Copyright (C) Scott Patterson, 2002. 
 * All rights reserved worldwide.
 *
 * This software is provided "as is" without express or implied
 * warranties. You may freely copy and compile this source into
 * applications you distribute provided that the copyright text
 * below is included in the resulting source code, for example:
 * "Portions Copyright (C) Scott Patterson, 2002"
 */


// FactoryIDs.h

#ifndef FACTORYIDS_H
#define FACTORYIDS_H

// AVLayer IDs
enum {
	FACTORY_ID_AVLAYER_INTRO,
	FACTORY_ID_AVLAYER_STARTMENU,
	FACTORY_ID_AVLAYER_GAMECONFIG,
	FACTORY_ID_AVLAYER_GAME,
	FACTORY_ID_AVLAYER_GAMEHUD,
	FACTORY_ID_AVLAYER_GAMEPAUSE,
	FACTORY_ID_AVLAYER_SYSTEMCONFIG,
	FACTORY_ID_AVLAYER_GAMEWIN,
	FACTORY_ID_AVLAYER_GAMELOSE,
	FACTORY_ID_AVLAYER_GAMEVIEWER,
	FACTORY_ID_AVLAYER_GAMEEDITOR,
	FACTORY_ID_AVLAYER_COUNT
};

// AVLayer Config IDs
enum {
	FACTORY_ID_AVLAYER_CONFIG_NONE,
	FACTORY_ID_AVLAYER_CONFIG_INTRO,
	FACTORY_ID_AVLAYER_CONFIG_STARTMENU,
	FACTORY_ID_AVLAYER_CONFIG_GAMECONFIG,
	FACTORY_ID_AVLAYER_CONFIG_GAME,
	FACTORY_ID_AVLAYER_CONFIG_GAMEHUD,
	FACTORY_ID_AVLAYER_CONFIG_GAMEPAUSE,
	FACTORY_ID_AVLAYER_CONFIG_SYSTEMCONFIG,
	FACTORY_ID_AVLAYER_CONFIG_GAMEWIN,
	FACTORY_ID_AVLAYER_CONFIG_GAMELOSE,
	FACTORY_ID_AVLAYER_CONFIG_GAMEVIEWER,
	FACTORY_ID_AVLAYER_CONFIG_GAMEEDITOR,
	FACTORY_ID_AVLAYER_CONFIG_COUNT
};

// LogicLayer IDs
enum {
	FACTORY_ID_LOGICLAYER_INTRO,
	FACTORY_ID_LOGICLAYER_STARTMENU,
	FACTORY_ID_LOGICLAYER_GAMECONFIG,
	FACTORY_ID_LOGICLAYER_GAME,
	FACTORY_ID_LOGICLAYER_GAMEPAUSE,
	FACTORY_ID_LOGICLAYER_SYSTEMCONFIG,
	FACTORY_ID_LOGICLAYER_GAMEWIN,
	FACTORY_ID_LOGICLAYER_GAMELOSE,
	FACTORY_ID_LOGICLAYER_GAMEVIEWER,
	FACTORY_ID_LOGICLAYER_GAMEEDITOR,
	FACTORY_ID_LOGICLAYER_COUNT
};

// LogicLayer Config IDs
enum {
	FACTORY_ID_LOGICLAYER_CONFIG_NONE,
	FACTORY_ID_LOGICLAYER_CONFIG_INTRO,
	FACTORY_ID_LOGICLAYER_CONFIG_STARTMENU,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMECONFIG,
	FACTORY_ID_LOGICLAYER_CONFIG_GAME,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMEPAUSE,
	FACTORY_ID_LOGICLAYER_CONFIG_SYSTEMCONFIG,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMEWIN,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMELOSE,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMEVIEWER,
	FACTORY_ID_LOGICLAYER_CONFIG_GAMEEDITOR,
	FACTORY_ID_LOGICLAYER_CONFIG_COUNT
};

// Task IDs
enum {
	FACTORY_ID_TASK_FRAME_PLAYER,
	FACTORY_ID_TASK_START_APP,
	FACTORY_ID_TASK_CHANGE_DRIVER,
	FACTORY_ID_TASK_COUNT
};

// Task Config IDs
enum {
	FACTORY_ID_TASK_CONFIG_NONE,
	FACTORY_ID_TASK_CONFIG_INTRO,
	FACTORY_ID_TASK_CONFIG_GAME,
	FACTORY_ID_TASK_CONFIG_GAMECONFIG,
	FACTORY_ID_TASK_CONFIG_SYSTEMCONFIG,
	FACTORY_ID_TASK_CONFIG_COUNT
};

#endif