#ifndef _HEADERS_H
#define _HEADERS_H

// Network header files (must be included before windows.h)
#include "..\NetLib\MTUDP.h"

// Windows Header Files:
#include <windows.h>
#include <mmsystem.h>

#include <ddraw.h>
#include <d3d.h>
#include <dsound.h>
#include <dinput.h>

// C RunTime Header Files
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include <assert.h>

// Local Header Files
#include "..\math3d\point3.h"
#include "..\math3d\matrix4.h"
#include "..\math3d\point3.h"
#include "..\math3d\mathd3d.h"
#include "..\math3d\plane3.h"
#include "..\math3d\polygon.h"
#include "..\math3d\tri.h"

#include "..\gamelib\GameGlobals.h"
#include "..\gamelib\GameErrors.h"
#include "..\gamelib\GameInterfaces.h"
#include "..\gamelib\GameTypes.h"
#include "..\gamelib\File.h"
#include "..\gamelib\Application.h"
#include "..\gamelib\Window.h"
#include "..\gamelib\GraphicsLayer.h"
#include "..\gamelib\model.h"
#include "..\gamelib\texture.h"
#include "..\gamelib\Keyboard.h"
#include "..\gamelib\Mouse.h"
#include "..\gamelib\InputLayer.h"
#include "..\gamelib\SoundLayer.h"
#include "..\gamelib\Sound.h"

#endif // Network header files (must be included before windows.h)
#include "..\NetLib\MTUDP.h"

// Windows Header Files:
#include <windows.h>
#include <mmsystem.h>

#include <ddraw.h>
#include <d3d.h>
#include <dsound.h>
#include <dinput.h>

// C RunTime Header Files
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include <assert.h>

// Local Header Files
#include "..\math3d\point3.h"
#include "..\math3d\matrix4.h"
#include "..\math3d\point3.h"
#include "..\math3d\mathd3d.h"
#include "..\math3d\plane3.h"
#include "..\math3d\polygon.h"
#include "..\math3d\tri.h"

#include "..\gamelib\GameGlobals.h"
#include "..\gamelib\GameErrors.h"
#include "..\gamelib\GameInterfaces.h"
#include "..\gamelib\GameTypes.h"
#include "..\gamelib\File.h"
#include "..\gamelib\Application.h"
#include "..\gamelib\Window.h"
#include "..\gamelib\GraphicsLayer.h"
#include "..\gamelib\model.h"
#include "..\gamelib\texture.h"
#include "..\gamelib\Keyboard.h"
#include "..\gamelib\Mouse.h"
#include "..\gamelib\InputLayer.h"
#include "..\gamelib\SoundLayer.h"
#include "..\gamelib\Sound.h"

#endif //_HEADERS_H