/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)


/*  Header for class ptc/Color  */

#ifndef _Included_ptc_Color
#define _Included_ptc_Color

#define Hptc_Color Classptc_Color
typedef struct Classptc_Color {
#include <pshpack4.h>
    long MSReserved;
    long index;
    float r;
    float g;
    float b;
    float a;
    /*boolean*/ long direct;
    /*boolean*/ long indexed;
#include <poppack.h>
} Classptc_Color;

typedef struct ClassArrayOfptc_Color {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_Color * const body[1];
} ClassArrayOfptc_Color;
#define HArrayOfptc_Color ClassArrayOfptc_Color
#define ArrayOfptc_Color ClassArrayOfptc_Color

#endif  /* _Included_ptc_Color */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

