/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)

struct Classjava_lang_String;
#define Hjava_lang_String Classjava_lang_String
struct Classptc_Format;
#define Hptc_Format Classptc_Format
struct Classptc_Mode;
#define Hptc_Mode Classptc_Mode
struct Classptc_Area;
#define Hptc_Area Classptc_Area
struct Classptc_Key;
#define Hptc_Key Classptc_Key
struct Classptc_base_Surface;
#define Hptc_base_Surface Classptc_base_Surface
struct Classptc_Palette;
#define Hptc_Palette Classptc_Palette
struct Classptc_Color;
#define Hptc_Color Classptc_Color

/*  Header for class ptc/rni/Console  */

#ifndef _Included_ptc_rni_Console
#define _Included_ptc_rni_Console

#define Hptc_rni_Console Classptc_rni_Console
typedef struct Classptc_rni_Console {
#include <pshpack4.h>
    long MSReserved;
    int64_t object;
#include <poppack.h>
} Classptc_rni_Console;

typedef struct ClassArrayOfptc_rni_Console {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_rni_Console * const body[1];
} ClassArrayOfptc_rni_Console;
#define HArrayOfptc_rni_Console ClassArrayOfptc_rni_Console
#define ArrayOfptc_rni_Console ClassArrayOfptc_rni_Console

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) int64_t __cdecl ptc_rni_Console_create (struct Hptc_rni_Console *);
__declspec(dllexport) void __cdecl ptc_rni_Console_destroy (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_configure (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *);
__declspec(dllexport) /*boolean*/ long __cdecl ptc_rni_Console_option (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *);
__declspec(dllexport) struct HArrayOfObject * __cdecl ptc_rni_Console_modes (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_open_1 (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *, long);
__declspec(dllexport) void __cdecl ptc_rni_Console_open_2 (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *, struct Hptc_Format *, long);
__declspec(dllexport) void __cdecl ptc_rni_Console_open_3 (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *, long, long, struct Hptc_Format *, long);
__declspec(dllexport) void __cdecl ptc_rni_Console_open_4 (struct Hptc_rni_Console *, int64_t, struct Hjava_lang_String *, struct Hptc_Mode *, long);
__declspec(dllexport) void __cdecl ptc_rni_Console_close (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_flush (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_finish (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_update_1 (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_update_2 (struct Hptc_rni_Console *, int64_t, struct Hptc_Area *);
__declspec(dllexport) /*boolean*/ long __cdecl ptc_rni_Console_key (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hptc_Key * __cdecl ptc_rni_Console_read (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_copy_1 (struct Hptc_rni_Console *, int64_t, struct Hptc_base_Surface *);
__declspec(dllexport) void __cdecl ptc_rni_Console_copy_2 (struct Hptc_rni_Console *, int64_t, struct Hptc_base_Surface *, struct Hptc_Area *, struct Hptc_Area *);
__declspec(dllexport) HObject * __cdecl ptc_rni_Console_lock (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_unlock (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_load_1 (struct Hptc_rni_Console *, int64_t, HObject *, long, long, long, struct Hptc_Format *, struct Hptc_Palette *);
__declspec(dllexport) void __cdecl ptc_rni_Console_load_2 (struct Hptc_rni_Console *, int64_t, HObject *, long, long, long, struct Hptc_Format *, struct Hptc_Palette *, struct Hptc_Area *, struct Hptc_Area *);
__declspec(dllexport) void __cdecl ptc_rni_Console_save_1 (struct Hptc_rni_Console *, int64_t, HObject *, long, long, long, struct Hptc_Format *, struct Hptc_Palette *);
__declspec(dllexport) void __cdecl ptc_rni_Console_save_2 (struct Hptc_rni_Console *, int64_t, HObject *, long, long, long, struct Hptc_Format *, struct Hptc_Palette *, struct Hptc_Area *, struct Hptc_Area *);
__declspec(dllexport) void __cdecl ptc_rni_Console_clear_1 (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_clear_2 (struct Hptc_rni_Console *, int64_t, struct Hptc_Color *);
__declspec(dllexport) void __cdecl ptc_rni_Console_clear_3 (struct Hptc_rni_Console *, int64_t, struct Hptc_Color *, struct Hptc_Area *);
__declspec(dllexport) void __cdecl ptc_rni_Console_palette_1 (struct Hptc_rni_Console *, int64_t, struct Hptc_Palette *);
__declspec(dllexport) struct Hptc_Palette * __cdecl ptc_rni_Console_palette_2 (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Console_clip_1 (struct Hptc_rni_Console *, int64_t, struct Hptc_Area *);
__declspec(dllexport) long __cdecl ptc_rni_Console_width (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) long __cdecl ptc_rni_Console_height (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) long __cdecl ptc_rni_Console_pages (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) long __cdecl ptc_rni_Console_pitch (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hptc_Area * __cdecl ptc_rni_Console_area (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hptc_Area * __cdecl ptc_rni_Console_clip_2 (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hptc_Format * __cdecl ptc_rni_Console_format (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hjava_lang_String * __cdecl ptc_rni_Console_name (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hjava_lang_String * __cdecl ptc_rni_Console_title (struct Hptc_rni_Console *, int64_t);
__declspec(dllexport) struct Hjava_lang_String * __cdecl ptc_rni_Console_information (struct Hptc_rni_Console *, int64_t);
#ifdef __cplusplus
}
#endif

#endif  /* _Included_ptc_rni_Console */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

