/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)

struct Classptc_Format;
#define Hptc_Format Classptc_Format
struct Classptc_Palette;
#define Hptc_Palette Classptc_Palette
struct Classjava_lang_String;
#define Hjava_lang_String Classjava_lang_String

/*  Header for class ptc/rni/Copy  */

#ifndef _Included_ptc_rni_Copy
#define _Included_ptc_rni_Copy

#define Hptc_rni_Copy Classptc_rni_Copy
typedef struct Classptc_rni_Copy {
#include <pshpack4.h>
    long MSReserved;
    int64_t object;
#include <poppack.h>
} Classptc_rni_Copy;

typedef struct ClassArrayOfptc_rni_Copy {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_rni_Copy * const body[1];
} ClassArrayOfptc_rni_Copy;
#define HArrayOfptc_rni_Copy ClassArrayOfptc_rni_Copy
#define ArrayOfptc_rni_Copy ClassArrayOfptc_rni_Copy

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) int64_t __cdecl ptc_rni_Copy_create (struct Hptc_rni_Copy *);
__declspec(dllexport) void __cdecl ptc_rni_Copy_destroy (struct Hptc_rni_Copy *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Copy_request (struct Hptc_rni_Copy *, int64_t, struct Hptc_Format *, struct Hptc_Format *);
__declspec(dllexport) void __cdecl ptc_rni_Copy_palette (struct Hptc_rni_Copy *, int64_t, struct Hptc_Palette *, struct Hptc_Palette *);
__declspec(dllexport) void __cdecl ptc_rni_Copy_copy (struct Hptc_rni_Copy *, int64_t, HObject *, long, long, long, long, long, HObject *, long, long, long, long, long);
__declspec(dllexport) /*boolean*/ long __cdecl ptc_rni_Copy_option (struct Hptc_rni_Copy *, int64_t, struct Hjava_lang_String *);
#ifdef __cplusplus
}
#endif

#endif  /* _Included_ptc_rni_Copy */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

