/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)


/*  Header for class ptc/Format  */

#ifndef _Included_ptc_Format
#define _Included_ptc_Format

#define Hptc_Format Classptc_Format
typedef struct Classptc_Format {
#include <pshpack4.h>
    long MSReserved;
    long r;
    long g;
    long b;
    long a;
    long bits;
    /*boolean*/ long direct;
    /*boolean*/ long indexed;
#include <poppack.h>
} Classptc_Format;

typedef struct ClassArrayOfptc_Format {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_Format * const body[1];
} ClassArrayOfptc_Format;
#define HArrayOfptc_Format ClassArrayOfptc_Format
#define ArrayOfptc_Format ClassArrayOfptc_Format

#endif  /* _Included_ptc_Format */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

