/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)


/*  Header for class ptc/Key  */

#ifndef _Included_ptc_Key
#define _Included_ptc_Key

#define Hptc_Key Classptc_Key
typedef struct Classptc_Key {
#include <pshpack4.h>
    long MSReserved;
#define ptc_Key_ENTER 10
#define ptc_Key_BACKSPACE 8
#define ptc_Key_TAB 9
#define ptc_Key_CANCEL 3
#define ptc_Key_CLEAR 12
#define ptc_Key_SHIFT 16
#define ptc_Key_CONTROL 17
#define ptc_Key_ALT 18
#define ptc_Key_PAUSE 19
#define ptc_Key_CAPSLOCK 20
#define ptc_Key_ESCAPE 27
#define ptc_Key_SPACE 32
#define ptc_Key_PAGEUP 33
#define ptc_Key_PAGEDOWN 34
#define ptc_Key_END 35
#define ptc_Key_HOME 36
#define ptc_Key_LEFT 37
#define ptc_Key_UP 38
#define ptc_Key_RIGHT 39
#define ptc_Key_DOWN 40
#define ptc_Key_COMMA 44
#define ptc_Key_PERIOD 46
#define ptc_Key_SLASH 47
#define ptc_Key_ZERO 48
#define ptc_Key_ONE 49
#define ptc_Key_TWO 50
#define ptc_Key_THREE 51
#define ptc_Key_FOUR 52
#define ptc_Key_FIVE 53
#define ptc_Key_SIX 54
#define ptc_Key_SEVEN 55
#define ptc_Key_EIGHT 56
#define ptc_Key_NINE 57
#define ptc_Key_SEMICOLON 59
#define ptc_Key_EQUALS 61
#define ptc_Key_A 65
#define ptc_Key_B 66
#define ptc_Key_C 67
#define ptc_Key_D 68
#define ptc_Key_E 69
#define ptc_Key_F 70
#define ptc_Key_G 71
#define ptc_Key_H 72
#define ptc_Key_I 73
#define ptc_Key_J 74
#define ptc_Key_K 75
#define ptc_Key_L 76
#define ptc_Key_M 77
#define ptc_Key_N 78
#define ptc_Key_O 79
#define ptc_Key_P 80
#define ptc_Key_Q 81
#define ptc_Key_R 82
#define ptc_Key_S 83
#define ptc_Key_T 84
#define ptc_Key_U 85
#define ptc_Key_V 86
#define ptc_Key_W 87
#define ptc_Key_X 88
#define ptc_Key_Y 89
#define ptc_Key_Z 90
#define ptc_Key_OPENBRACKET 91
#define ptc_Key_BACKSLASH 92
#define ptc_Key_CLOSEBRACKET 93
#define ptc_Key_NUMPAD0 96
#define ptc_Key_NUMPAD1 97
#define ptc_Key_NUMPAD2 98
#define ptc_Key_NUMPAD3 99
#define ptc_Key_NUMPAD4 100
#define ptc_Key_NUMPAD5 101
#define ptc_Key_NUMPAD6 102
#define ptc_Key_NUMPAD7 103
#define ptc_Key_NUMPAD8 104
#define ptc_Key_NUMPAD9 105
#define ptc_Key_MULTIPLY 106
#define ptc_Key_ADD 107
#define ptc_Key_SEPARATOR 108
#define ptc_Key_SUBTRACT 109
#define ptc_Key_DECIMAL 110
#define ptc_Key_DIVIDE 111
#define ptc_Key_F1 112
#define ptc_Key_F2 113
#define ptc_Key_F3 114
#define ptc_Key_F4 115
#define ptc_Key_F5 116
#define ptc_Key_F6 117
#define ptc_Key_F7 118
#define ptc_Key_F8 119
#define ptc_Key_F9 120
#define ptc_Key_F10 121
#define ptc_Key_F11 122
#define ptc_Key_F12 123
#define ptc_Key_DELETE 127
#define ptc_Key_NUMLOCK 144
#define ptc_Key_SCROLLLOCK 145
#define ptc_Key_PRINTSCREEN 154
#define ptc_Key_INSERT 155
#define ptc_Key_HELP 156
#define ptc_Key_META 157
#define ptc_Key_BACKQUOTE 192
#define ptc_Key_QUOTE 222
#define ptc_Key_FINAL 24
#define ptc_Key_CONVERT 28
#define ptc_Key_NONCONVERT 29
#define ptc_Key_ACCEPT 30
#define ptc_Key_MODECHANGE 31
#define ptc_Key_KANA 21
#define ptc_Key_KANJI 25
#define ptc_Key_UNDEFINED 0
    long code;
    /*boolean*/ long alt;
    /*boolean*/ long shift;
    /*boolean*/ long control;
#include <poppack.h>
} Classptc_Key;

typedef struct ClassArrayOfptc_Key {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_Key * const body[1];
} ClassArrayOfptc_Key;
#define HArrayOfptc_Key ClassArrayOfptc_Key
#define ArrayOfptc_Key ClassArrayOfptc_Key

#endif  /* _Included_ptc_Key */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

