/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)

struct Classptc_Format;
#define Hptc_Format Classptc_Format

/*  Header for class ptc/Mode  */

#ifndef _Included_ptc_Mode
#define _Included_ptc_Mode

#define Hptc_Mode Classptc_Mode
typedef struct Classptc_Mode {
#include <pshpack4.h>
    long MSReserved;
    /*boolean*/ long valid;
    long width;
    long height;
    struct Hptc_Format * const format;
#include <poppack.h>
} Classptc_Mode;

typedef struct ClassArrayOfptc_Mode {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_Mode * const body[1];
} ClassArrayOfptc_Mode;
#define HArrayOfptc_Mode ClassArrayOfptc_Mode
#define ArrayOfptc_Mode ClassArrayOfptc_Mode

#endif  /* _Included_ptc_Mode */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

