/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)


/*  Header for class ptc/Palette  */

#ifndef _Included_ptc_Palette
#define _Included_ptc_Palette

#define Hptc_Palette Classptc_Palette
typedef struct Classptc_Palette {
#include <pshpack4.h>
    long MSReserved;
    /*boolean*/ long locked;
    struct HArrayOfInt * const data;
#include <poppack.h>
} Classptc_Palette;

typedef struct ClassArrayOfptc_Palette {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_Palette * const body[1];
} ClassArrayOfptc_Palette;
#define HArrayOfptc_Palette ClassArrayOfptc_Palette
#define ArrayOfptc_Palette ClassArrayOfptc_Palette

#endif  /* _Included_ptc_Palette */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

