/*  DO NOT EDIT - automatically generated by msjavah  */
#include <native.h>
#pragma warning(disable:4510)
#pragma warning(disable:4512)
#pragma warning(disable:4610)


/*  Header for class ptc/rni/Timer  */

#ifndef _Included_ptc_rni_Timer
#define _Included_ptc_rni_Timer

#define Hptc_rni_Timer Classptc_rni_Timer
typedef struct Classptc_rni_Timer {
#include <pshpack4.h>
    long MSReserved;
    int64_t object;
#include <poppack.h>
} Classptc_rni_Timer;

typedef struct ClassArrayOfptc_rni_Timer {
    int32_t MSReserved;
    const unsigned long length;
    Hptc_rni_Timer * const body[1];
} ClassArrayOfptc_rni_Timer;
#define HArrayOfptc_rni_Timer ClassArrayOfptc_rni_Timer
#define ArrayOfptc_rni_Timer ClassArrayOfptc_rni_Timer

#ifdef __cplusplus
extern "C" {
#endif
__declspec(dllexport) int64_t __cdecl ptc_rni_Timer_create (struct Hptc_rni_Timer *);
__declspec(dllexport) void __cdecl ptc_rni_Timer_destroy (struct Hptc_rni_Timer *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Timer_set (struct Hptc_rni_Timer *, int64_t, double);
__declspec(dllexport) void __cdecl ptc_rni_Timer_start (struct Hptc_rni_Timer *, int64_t);
__declspec(dllexport) void __cdecl ptc_rni_Timer_stop (struct Hptc_rni_Timer *, int64_t);
__declspec(dllexport) double __cdecl ptc_rni_Timer_time (struct Hptc_rni_Timer *, int64_t);
__declspec(dllexport) double __cdecl ptc_rni_Timer_delta (struct Hptc_rni_Timer *, int64_t);
__declspec(dllexport) double __cdecl ptc_rni_Timer_resolution (struct Hptc_rni_Timer *, int64_t);
#ifdef __cplusplus
}
#endif

#endif  /* _Included_ptc_rni_Timer */

#pragma warning(default:4510)
#pragma warning(default:4512)
#pragma warning(default:4610)

