
all: deque list vector map

deque: deque.cpp
	$(CXX) -o $@ $< $(LOADLIBES)

list: list.cpp
	$(CXX) -o $@ $< $(LOADLIBES)

vector: vector.cpp
	$(CXX) -o $@ $< $(LOADLIBES)

map: map.cpp
	$(CXX) -o $@ $< $(LOADLIBES)
