CC = g++ -Wall -ansi

all:
	$(CC) -c ../../../source/TokenStream.cpp -I /usr/include -I ../../../source
	$(CC) -c ../../../source/PropertyScript.cpp -I /usr/include -I ../../../source

clean:
	@echo Cleaning up...
	@rm TokenStream
	@rm PropertyScript
	@echo Done.
