// Magic Software, Inc.
// http://www.magic-software.com
// http://www.wild-magic.com
// Copyright (c) 2004.  All Rights Reserved
//
// The Wild Magic Library (WM3) source code is supplied under the terms of
// the license agreement http://www.wild-magic.com/License/WildMagic3.pdf and
// may not be copied or disclosed except in accordance with the terms of that
// agreement.

#include "Wm3CharcoalVShader.h"
using namespace Wm3;

WM3_IMPLEMENT_RTTI(Wm3,CharcoalVShader,VertexShader);
WM3_IMPLEMENT_STREAM(CharcoalVShader);
WM3_IMPLEMENT_DEFAULT_STREAM(CharcoalVShader,VertexShader);
WM3_IMPLEMENT_DEFAULT_NAME_ID(CharcoalVShader,VertexShader);

//----------------------------------------------------------------------------
CharcoalVShader::CharcoalVShader ()
{
    // shader program (load the type of the current renderer)
    m_acProgram = ms_aacProgram[Renderer::GetType()];

    // shader constants
    int iType, iOption, iReg, iRegQuantity;
    ShaderConstant* pkConst;

    // model-to-view * projection matrix (4x4)
    iType = ShaderConstant::SC_TRANSFORM_MVP;
    iOption = ShaderConstant::SCO_MATRIX;
    iReg = 0;
    iRegQuantity = 4;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // model-to-world matrix (4x4)
    iType = ShaderConstant::SC_TRANSFORM_M;
    iOption = ShaderConstant::SCO_MATRIX;
    iReg = 4;
    iRegQuantity = 4;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // user defined vector (register 8)
    // AmbientIntensity
    iType = ShaderConstant::SC_USER_DEFINED;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 8;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // user defined vector (register 9)
    // ContrastExponent
    iType = ShaderConstant::SC_USER_DEFINED;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 9;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // light direction 0 vector (x,y,z,0)
    iType = ShaderConstant::SC_LIGHT_DIRECTION;
    iOption = ShaderConstant::SCO_LIGHT0;
    iReg = 10;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // light direction 1 vector (x,y,z,0)
    iType = ShaderConstant::SC_LIGHT_DIRECTION;
    iOption = ShaderConstant::SCO_LIGHT1;
    iReg = 11;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    m_kConstant.Append(pkConst);

    // numerical constant vector (register 12)
    iType = ShaderConstant::SC_NUMERICAL_CONSTANT;
    iOption = ShaderConstant::SCO_NONE;
    iReg = 12;
    iRegQuantity = 1;
    pkConst = new ShaderConstant(iType,iOption,iReg,iRegQuantity);
    pkConst->SetRegisterData(0,0.000000f,1.00000f,2.00000f,0.500000f);
    m_kConstant.Append(pkConst);
}
//----------------------------------------------------------------------------
CharcoalVShader::~CharcoalVShader ()
{
}
//----------------------------------------------------------------------------
const char* CharcoalVShader::ms_aacProgram[Renderer::RT_QUANTITY] =
{
"!!ARBvp1.0\n"
"# ARB_vertex_program generated by NVIDIA Cg compiler\n"
"# cgc version 1.1.0003, build date Jul  7 2003  11:55:19\n"
"# command line args: -q -profile arbvp1 -entry vmain\n"
"# nv30vp backend compiling 'vmain' program\n"
"PARAM c12 = { 0, 1, 2, 0.5 };\n"
"#vendor NVIDIA Corporation\n"
"#version 1.0.02\n"
"#profile arbvp1\n"
"#program vmain\n"
"#semantic vmain.Wm3TransformMVP\n"
"#semantic vmain.Wm3TransformM\n"
"#semantic vmain.AmbientIntensity\n"
"#semantic vmain.ContrastExponent\n"
"#semantic vmain.Wm3LightDirection0\n"
"#semantic vmain.Wm3LightDirection1\n"
"#var float4 i_f4Position : $vin.POSITION : POSITION : 0 : 1\n"
"#var float3 i_f3Normal : $vin.NORMAL : NORMAL : 1 : 1\n"
"#var float2 i_f2TexCoord : $vin.TEXCOORD0 : TEXCOORD0 : 2 : 1\n"
"#var float4 o_f4Position : $vout.POSITION : POSITION : 3 : 1\n"
"#var float4 o_f4Color : $vout.COLOR : COLOR : 4 : 1\n"
"#var float2 o_f2TexCon : $vout.TEXCOORD0 : TEXCOORD0 : 5 : 1\n"
"#var float2 o_f2TexRan : $vout.TEXCOORD1 : TEXCOORD1 : 6 : 1\n"
"#var float2 o_f2TexPap : $vout.TEXCOORD2 : TEXCOORD2 : 7 : 1\n"
"#var float4x4 Wm3TransformMVP :  : c[0], 4 : 8 : 1\n"
"#var float4x4 Wm3TransformM :  : c[4], 4 : 9 : 1\n"
"#var float AmbientIntensity :  : c[8] : 10 : 1\n"
"#var float ContrastExponent :  : c[9] : 11 : 1\n"
"#var float3 Wm3LightDirection0 :  : c[10] : 12 : 1\n"
"#var float3 Wm3LightDirection1 :  : c[11] : 13 : 1\n"
"TEMP R0, R1, R2;\n"
"ATTRIB v24 = vertex.texcoord[0];\n"
"ATTRIB v18 = vertex.normal;\n"
"ATTRIB v16 = vertex.position;\n"
"PARAM c9 = program.local[9];\n"
"PARAM c8 = program.local[8];\n"
"PARAM c11 = program.local[11];\n"
"PARAM c10 = program.local[10];\n"
"PARAM c4[4] = { program.local[4..7] };\n"
"PARAM c0[4] = { program.local[0..3] };\n"
"	MOV result.texcoord[1].xy, v24;\n"
"	DP4 R0.x, c0[0], v16;\n"
"	DP4 R0.y, c0[1], v16;\n"
"	DP4 R0.z, c0[2], v16;\n"
"	DP4 R0.w, c0[3], v16;\n"
"	MOV result.position, R0;\n"
"	DP3 R2.x, c4[0].xyzx, v18.xyzx;\n"
"	DP3 R2.y, c4[1].xyzx, v18.xyzx;\n"
"	DP3 R2.z, c4[2].xyzx, v18.xyzx;\n"
"	DP3 R1.x, R2.xyzx, c10.xyzx;\n"
"	MIN R1.x, c12.y, -R1.x;\n"
"	MAX R1.y, c12.x, R1.x;\n"
"	DP3 R1.x, R2.xyzx, c11.xyzx;\n"
"	MIN R1.x, c12.y, -R1.x;\n"
"	MAX R1.x, c12.x, R1.x;\n"
"	ADD R1.x, R1.y, R1.x;\n"
"	ADD R1.x, R1.x, c8.x;\n"
"	MIN R1.x, c12.y, R1.x;\n"
"	MAX R1.xy, c12.x, R1.x;\n"
"	MOV R1.zw, c9.x;\n"
"	LIT R1.z, R1;\n"
"	MOV result.color.front.primary, R1.z;\n"
"	MOV result.texcoord[0].x, c12.x;\n"
"	MOV result.texcoord[0].y, R1.z;\n"
"	RCP R1.x, R0.w;\n"
"	MAD R0.xy, R0.xyxx, R1.x, c12.y;\n"
"	MUL result.texcoord[2].xy, R0.xyxx, c12.w;\n"
"END\n"
"# 27 instructions\n"
"# 3 temp registers\n"
"# End of program\n"
,
"vs_1_1\n"
"// DX9 Vertex shader generated by NVIDIA Cg compiler\n"
"// cgc version 1.1.0003, build date Jul  7 2003  11:55:19\n"
"// command line args: -q -profile vs_1_1 -entry vmain -profileopts dcls -strict\n"
"// nv30vp backend compiling 'vmain' program\n"
"def c12, 0, 1, 2, 0.5\n"
"//vendor NVIDIA Corporation\n"
"//version 1.0.02\n"
"//profile vs_1_1\n"
"//program vmain\n"
"//semantic vmain.Wm3TransformMVP\n"
"//semantic vmain.Wm3TransformM\n"
"//semantic vmain.AmbientIntensity\n"
"//semantic vmain.ContrastExponent\n"
"//semantic vmain.Wm3LightDirection0\n"
"//semantic vmain.Wm3LightDirection1\n"
"//var float4 i_f4Position : $vin.POSITION : POSITION : 0 : 1\n"
"//var float3 i_f3Normal : $vin.NORMAL : NORMAL : 1 : 1\n"
"//var float2 i_f2TexCoord : $vin.TEXCOORD0 : TEXCOORD0 : 2 : 1\n"
"//var float4 o_f4Position : $vout.POSITION : POSITION : 3 : 1\n"
"//var float4 o_f4Color : $vout.COLOR : COLOR : 4 : 1\n"
"//var float2 o_f2TexCon : $vout.TEXCOORD0 : TEXCOORD0 : 5 : 1\n"
"//var float2 o_f2TexRan : $vout.TEXCOORD1 : TEXCOORD1 : 6 : 1\n"
"//var float2 o_f2TexPap : $vout.TEXCOORD2 : TEXCOORD2 : 7 : 1\n"
"//var float4x4 Wm3TransformMVP :  : c[0], 4 : 8 : 1\n"
"//var float4x4 Wm3TransformM :  : c[4], 4 : 9 : 1\n"
"//var float AmbientIntensity :  : c[8] : 10 : 1\n"
"//var float ContrastExponent :  : c[9] : 11 : 1\n"
"//var float3 Wm3LightDirection0 :  : c[10] : 12 : 1\n"
"//var float3 Wm3LightDirection1 :  : c[11] : 13 : 1\n"
"//const c[12] = 0 1 2 0.5\n"
"dcl_texcoord0 v7\n"
"dcl_normal v3\n"
"dcl_position v0\n"
"	mov oT1.xy, v7\n"
"	dp4 r0.x, c0, v0\n"
"	dp4 r0.y, c1, v0\n"
"	dp4 r0.z, c2, v0\n"
"	dp4 r0.w, c3, v0\n"
"	mov oPos, r0\n"
"	dp3 r2.x, c4.xyz, v3.xyz\n"
"	dp3 r2.y, c5.xyz, v3.xyz\n"
"	dp3 r2.z, c6.xyz, v3.xyz\n"
"	dp3 r1.x, r2.xyz, c10.xyz\n"
"	min r1.x, c12.y, -r1.x\n"
"	max r1.y, c12.x, r1.x\n"
"	dp3 r1.x, r2.xyz, c11.xyz\n"
"	min r1.x, c12.y, -r1.x\n"
"	max r1.x, c12.x, r1.x\n"
"	add r1.x, r1.y, r1.x\n"
"	add r1.x, r1.x, c8.x\n"
"	min r1.x, c12.y, r1.x\n"
"	max r1.xy, c12.x, r1.x\n"
"	mov r1.zw, c9.x\n"
"	lit r1.z, r1\n"
"	mov oD0, r1.z\n"
"	mov oT0.x, c12.x\n"
"	mov oT0.y, r1.z\n"
"	rcp r1.x, r0.w\n"
"	mad r0.xy, r0.xy, r1.x, c12.y\n"
"	mul oT2.xy, r0.xy, c12.w\n"
"// 27 instructions\n"
"// 3 temp registers\n"
"// End of program\n"
};
